# Generated by Django 4.2.11 on 2024-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='user avatar.png', upload_to='profile_images'),
        ),
    ]
