# Generated by Django 4.2.11 on 2024-10-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
    ]
