# Generated by Django 4.2.11 on 2024-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_userrank_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(upload_to='quiz'),
        ),
    ]
